# Generated by Django 3.2.7 on 2022-04-03 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.CharField(default=tasks.models.getID, editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_on', models.FloatField(default=tasks.models.getCurrentUnixTime)),
                ('status', models.CharField(choices=[('UR', 'Under Reveiw'), ('RS', 'Resolved'), ('OP', 'Open')], default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('priority', models.CharField(default='nl', max_length=3)),
                ('description', models.TextField()),
                ('created_on', models.FloatField(default=tasks.models.getCurrentUnixTime, editable=False)),
                ('starts_on', models.FloatField(blank=True, null=True)),
                ('ends_on', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(choices=[('mn', 'Main task'), ('sub', 'Sub task')], default='mn', max_length=3)),
                ('assigne', models.ManyToManyField(blank=True, related_name='assigne', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.CharField(default=tasks.models.getID, editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField()),
                ('created_on', models.FloatField(default=tasks.models.getCurrentUnixTime)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.CharField(default=tasks.models.getID, editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField()),
                ('created_on', models.FloatField(default=tasks.models.getCurrentUnixTime)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
