# Generated by Django 3.2.7 on 2022-04-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0002_auto_20220405_2056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('id', 'project')},
        ),
    ]
